apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: dev
  labels:
    app: mongodb
spec:
  clusterIP: None # Headless service for direct pod communication
  ports:
    - port: 27017 # Port for MongoDB
      targetPort: 27017 # Port on the MongoDB container
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb # Selects pods with label 'app: mongodb'
