apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: shivanibhukya/frontend:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend.naveenops.live/api/tasks"
          ports:
            - containerPort: 3000
